# Generated by Django 4.2 on 2024-09-06 04:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_tags'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products_Images',
            new_name='ProductsImages',
        ),
    ]
