# Generated by Django 4.2 on 2024-09-07 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_products_images_productsimages'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(default='', upload_to='product/'),
            preserve_default=False,
        ),
    ]
