# Generated by Django 4.2 on 2024-09-07 01:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='img',
            new_name='image',
        ),
    ]
