# Generated by Django 4.2 on 2024-09-07 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_rename_img_productsimages_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsimages',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Product_image', to='products.product'),
        ),
    ]
