# Generated by Django 4.2 on 2024-09-11 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_brand_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='img',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='img',
            new_name='image',
        ),
    ]
